<a href="https://colab.research.google.com/github/SpectreB/Python-class/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
print(pd.__version__)

1.5.3

In [ ]:
df=pd.read_csv("/content/Educational_Attainment_20231027.csv")

In [ ]:
pd.read_json
pd.read_csv

<function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols=None, squeeze: 'bool | None' = None, prefix: 'str | lib.NoDefault' = <no_default>, mangle_dupe_cols: 'bool' = True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace: 'bool' = False, skiprows=None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values=None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool' = False, skip_blank_lines: 'bool' = True, parse_dates=None, infer_datetime_format: 'bool' = False, keep_date_col: 'bool' = False, date_parser=None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, error_bad_lines: 'bool | None' = None, warn_bad_lines: 'bool | None' = None, on_bad_lines=None, delim_whitespace: 'bool' = False, low_memory=True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions' = None) -> 'DataFrame | TextFileReader'>

In [ ]:
df.head(5)

,Geography,Geography type,Year,Less Than High School Graduate,High School Graduate,Some College or Associate's Degree,Bachelor's Degree or Higher,Location 1
0,Atherton,Town,2014,13.6,12.3,2.7,3.5,"(37.458611, -122.2)"
1,Colma,Town,2014,6.3,6.4,10.4,2.4,"(37.678889, -122.455556)"
2,Foster City,City,2014,11.9,9.7,2.0,2.9,"(37.551389, -122.266389)"
3,Portola Valley,Town,2014,48.1,0.0,0.0,1.8,"(37.375, -122.218611)"
4,Redwood City,City,2014,16.4,10.6,6.6,3.0,"(37.482778, -122.236111)"

In [ ]:
df.tail(10)

,Geography,Geography type,Year,Less Than High School Graduate,High School Graduate,Some College or Associate's Degree,Bachelor's Degree or Higher,Location 1
22,Loma Mar,CDP,2014,100.0,0.0,0.0,0.0,"(37.271111, -122.3075)"
23,Woodside,Town,2014,0.0,9.4,6.8,3.2,"(37.420833, -122.259722)"
24,Half Moon Bay,City,2014,9.5,4.0,0.7,1.4,"(37.458889, -122.436944)"
25,San Bruno,City,2014,7.7,7.7,7.0,3.0,"(37.625278, -122.425278)"
26,Pescadero,CDP,2014,44.4,0.0,0.0,0.0,"(37.255, -122.381389)"
27,El Granada,CDP,2014,9.2,4.3,9.1,2.4,"(37.503889, -122.473333)"
28,West Menlo Park,CDP,2014,37.8,0.0,5.7,3.6,"(37.433611, -122.203056)"
29,Montara,CDP,2014,3.3,0.0,0.0,0.0,"(37.539722, -122.506389)"
30,Burlingame,City,2014,20.1,8.3,7.4,3.7,"(37.583333, -122.363611)"
31,La Honda,CDP,2014,0.0,0.0,11.9,0.0,"(37.399444, -122.197222)"

In [ ]:
df.describe()

,Year,Less Than High School Graduate,High School Graduate,Some College or Associate's Degree,Bachelor's Degree or Higher
count,32.0,32.00000,32.000000,32.000000,32.000000
mean,2014.0,17.80000,6.462500,5.946875,2.856250
std,0.0,19.29944,4.693905,4.728430,1.873919
min,2014.0,0.00000,0.000000,0.000000,0.000000
25%,2014.0,6.82500,1.925000,2.525000,2.100000
50%,2014.0,13.90000,7.750000,5.500000,3.000000
75%,2014.0,20.97500,9.450000,8.800000,3.600000
max,2014.0,100.00000,16.400000,18.500000,9.100000

In [ ]:
df.drop("Geography", axis=1).describe(include="all")

,Geography type,Year,Less Than High School Graduate,High School Graduate,Some College or Associate's Degree,Bachelor's Degree or Higher,Location 1
count,32,32.0,32.00000,32.000000,32.000000,32.000000,32
unique,3,NaN,NaN,NaN,NaN,NaN,32
top,City,NaN,NaN,NaN,NaN,NaN,"(37.458611, -122.2)"
freq,15,NaN,NaN,NaN,NaN,NaN,1
mean,NaN,2014.0,17.80000,6.462500,5.946875,2.856250,NaN
std,NaN,0.0,19.29944,4.693905,4.728430,1.873919,NaN
min,NaN,2014.0,0.00000,0.000000,0.000000,0.000000,NaN
25%,NaN,2014.0,6.82500,1.925000,2.525000,2.100000,NaN
50%,NaN,2014.0,13.90000,7.750000,5.500000,3.000000,NaN
75%,NaN,2014.0,20.97500,9.450000,8.800000,3.600000,NaN
max,NaN,2014.0,100.00000,16.400000,18.500000,9.100000,NaN

In [ ]:
df.dttypes

In [ ]:
df.Geography.count()

32

In [ ]:
df.columns = df.columns.str.replace(' ' ,'')
df.columns= df.columns.str.replace("'", "")

                  Geography Geographytype  Year  LessThanHighSchoolGraduate  \
0                 Atherton          Town  2014                        13.6
1                    Colma          Town  2014                         6.3
2              Foster City          City  2014                        11.9
3           Portola Valley          Town  2014                        48.1
4             Redwood City          City  2014                        16.4
5                   Ladera           CDP  2014                         0.0
6               Moss Beach           CDP  2014                         4.8
7      South San Francisco          City  2014                        14.2
8                  Belmont          City  2014                        20.9
9                Daly City          City  2014                        13.4
10               San Mateo          City  2014                        16.1
11         North Fair Oaks           CDP  2014                        26.7
12      Emerald Lake Hills           CDP  2014                         6.2
13            Hillsborough          Town  2014                        31.1
14                Brisbane          City  2014                         0.0
15              Menlo Park          City  2014                        22.1
16                Pacifica          City  2014                        15.1
17              San Carlos          City  2014                         8.5
18  Highlands-Baywood Park           CDP  2014                        15.7
19          East Palo Alto          City  2014                        18.3
20               Broadmoor           CDP  2014                        21.2
21                Millbrae          City  2014                         7.0
22                Loma Mar           CDP  2014                       100.0
23                Woodside          Town  2014                         0.0
24           Half Moon Bay          City  2014                         9.5
25               San Bruno          City  2014                         7.7
26               Pescadero           CDP  2014                        44.4
27              El Granada           CDP  2014                         9.2
28         West Menlo Park           CDP  2014                        37.8
29                 Montara           CDP  2014                         3.3
30              Burlingame          City  2014                        20.1
31                La Honda           CDP  2014                         0.0

    HighSchoolGraduate  SomeCollegeorAssociatesDegree  \
0                 12.3                            2.7
1                  6.4                           10.4
2                  9.7                            2.0
3                  0.0                            0.0
4                 10.6                            6.6
5                  0.0                            0.0
6                  8.2                            9.3
7                  7.8                            4.4
8                  5.9                            5.0
9                  8.9                            6.1
10                 9.6                            6.5
11                13.4                           18.5
12                 2.0                            4.1
13                 6.1                            1.5
14                 1.7                           11.5
15                12.0                            8.7
16                 4.3                            4.3
17                 8.4                            4.4
18                13.6                           10.2
19                16.4                           17.2
20                 8.0                            3.0
21                 7.8                            5.3
22                 0.0                            0.0
23                 9.4                            6.8
24                 4.0                            0.7
25                 7.7                            7.0
26                 0.0                            0.0
27                 4.3                            9.1
28                 0.0                            5.7
29                 0.0                            0.0
30                 8.3                            7.4
31                 0.0                           11.9

    BachelorsDegreeorHigher                 Location1
0                       3.5       (37.458611, -122.2)
1                       2.4  (37.678889, -122.455556)
2                       2.9  (37.551389, -122.266389)
3                       1.8     (37.375, -122.218611)
4                       3.0  (37.482778, -122.236111)
5                       0.0  (37.319167, -122.274167)
6                       3.5  (37.525278, -122.512778)
7                       4.1  (37.656111, -122.425556)
8                       3.6  (37.518056, -122.291667)
9                       6.1  (37.686389, -122.468333)
10                      3.4  (37.554167, -122.313056)
11                      4.6  (37.475278, -122.203611)
12                      2.2  (37.464444, -122.266389)
13                      1.4  (37.560278, -122.356389)
14                      3.3  (37.680833, -122.419167)
15                      2.9  (37.452778, -122.183333)
16                      4.6  (37.622778, -122.485556)
17                      2.3      (37.4955, -122.2668)
18                      3.3     (37.525, -122.343333)
19                      9.1  (37.466944, -122.139722)
20                      2.4    (37.6925, -122.478889)
21                      3.7  (37.600833, -122.401389)
22                      0.0    (37.271111, -122.3075)
23                      3.2  (37.420833, -122.259722)
24                      1.4  (37.458889, -122.436944)
25                      3.0  (37.625278, -122.425278)
26                      0.0     (37.255, -122.381389)
27                      2.4  (37.503889, -122.473333)
28                      3.6  (37.433611, -122.203056)
29                      0.0  (37.539722, -122.506389)
30                      3.7  (37.583333, -122.363611)
31                      0.0  (37.399444, -122.197222)

In [ ]:
df.Geographytype.unique()

array(['Town', 'City', 'CDP'], dtype=object)

In [ ]:
df.LessThanHighSchoolGraduate.value_counts()

0.0      4
13.6     1
15.1     1
3.3      1
37.8     1
9.2      1
44.4     1
7.7      1
9.5      1
100.0    1
7.0      1
21.2     1
18.3     1
15.7     1
8.5      1
22.1     1
6.3      1
31.1     1
6.2      1
26.7     1
16.1     1
13.4     1
20.9     1
14.2     1
4.8      1
16.4     1
48.1     1
11.9     1
20.1     1
Name: LessThanHighSchoolGraduate, dtype: int64

In [ ]:
df2=pd.read_csv("/content/survey_results_schema.csv")

In [ ]:

df.LessThanHighSchoolGraduate.value_counts()

0.0      4
13.6     1
15.1     1
3.3      1
37.8     1
9.2      1
44.4     1
7.7      1
9.5      1
100.0    1
7.0      1
21.2     1
18.3     1
15.7     1
8.5      1
22.1     1
6.3      1
31.1     1
6.2      1
26.7     1
16.1     1
13.4     1
20.9     1
14.2     1
4.8      1
16.4     1
48.1     1
11.9     1
20.1     1
Name: LessThanHighSchoolGraduate, dtype: int64

In [ ]:

df2=pd.read_csv("/content/survey_results_schema.csv")

In [ ]:

df2.shape

(78, 6)

In [ ]:

pd.set_option("display.max_columns", 85)
pd.set_option("display.max_rows", 85)

In [ ]:

d1=pd.read_csv("/content/survey_results_publica.csv")
d1.loc[0, 'MainBranch':'ToolsTechHaveWorkedWith']
d1.loc[0:5, 'MainBranch':'RemoteWork']

,MainBranch,Age,Employment,RemoteWork
0,None of these,18-24 years old,NaN,NaN
1,I am a developer by profession,25-34 years old,"Employed, full-time",Remote
2,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)"
3,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)"
4,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote
5,I am a developer by profession,35-44 years old,"Employed, full-time",Remote

In [ ]:
def mapGeography(s) :
  if s=="Town" :
    return 1
  else :
    return 0

In [ ]:
df['geography_mapped_value'] = df.Geographytype.apply(mapGeography)

In [ ]:
baby_names=pd.read_csv("/content/US_Baby_Names_right.csv")

In [ ]:
baby_names.head(10)

   Unnamed: 0     Id      Name    Year Gender State  Count
0       11349  11350      Emma  2004.0      F    AK   62.0
1       11350  11351   Madison  2004.0      F    AK   48.0
2       11351  11352    Hannah  2004.0      F    AK   46.0
3       11352  11353     Grace  2004.0      F    AK   44.0
4       11353  11354     Emily  2004.0      F    AK   41.0
5       11354  11355   Abigail  2004.0      F    AK   37.0
6       11355  11356    Olivia  2004.0      F    AK   33.0
7       11356  11357  Isabella  2004.0      F    AK   30.0
8       11357  11358    Alyssa  2004.0      F    AK   29.0
9       11358  11359    Sophia  2004.0      F    AK   28.0

In [ ]:
del baby_names["Id"]

In [ ]:
del baby_names["Unnamed: 0"]

In [ ]:
'''def Parity(x) :

  nbMen=0
  nbWomen=0

  for i in range (x.length) :
    if i=='F' :
      nbWomen+=1
    else :
      nbMen+=1

  if NbWomen > nbMen :
'''

In [ ]:
baby_names['Gender'].value_counts()

F    222058
M    171960
Name: Gender, dtype: int64

In [ ]:

## 8
nb_unique_Name=baby_names["Name"].nunique()
print(f"number of different names in the dataset is : {nb_unique_Name}" )

number of different names in the dataset is : 14144

In [ ]:

## 9
Name_with_most_occurence=baby_names["Name"].value_counts().idxmax()
print(f" the name with the most occurences is {Name_with_most_occurence} ")

 the name with the most occurences is Riley

In [ ]:
"""
group by name
"""

names =baby_names.groupby("Name").sum()

<ipython-input-34-af74682ae55b>:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  names =baby_names.groupby("Name").sum()

In [ ]:
##10

"""
names_count=names.value_counts()
val_min_names_count=names_count.min()
List_of_mins_names=names[names['Name'].value_counts() == val_min_names_count]
print(f" the names with the least occurences are {List_of_mins_names} ")
"""
len(names[names.Count== names.Count.min()])

2051

In [ ]:
names[names.Count == names.Count.median()]

           Unnamed: 0         Id     Year  Count
Name
Alexsa        4845771  4845778.0  14049.0   44.0
Amna          7097802  7097809.0  14065.0   44.0
Arham         7303958  7303964.0  12068.0   44.0
Arrow         3840416  3840421.0  10067.0   44.0
Aryssa        3217786  3217792.0  12043.0   44.0
Babyboy       4846158  4846163.0  10022.0   44.0
Bellamy       6028708  6028715.0  14091.0   44.0
Dajon         8042684  8042692.0  16057.0   44.0
Davianna      8582744  8582752.0  16063.0   44.0
Devean        2048571  2048574.0   6015.0   44.0
Elexa         4069919  4069926.0  14055.0   44.0
Emmersyn      8577977  8577985.0  16098.0   44.0
Esabella      3817581  3817587.0  12064.0   44.0
Favio         3453498  3453503.0  10038.0   44.0
Jaclynn       3818036  3818043.0  14065.0   44.0
Jakhari       7221878  7221885.0  14071.0   44.0
Jayanna       6634776  6634783.0  14062.0   44.0
Jennalyn      3769171  3769178.0  14053.0   44.0
Jiovanny      5303419  5303426.0  14058.0   44.0
Jori          9763182  9763189.0  14056.0   44.0
Juanluis      4843252  4843259.0  14055.0   44.0
Kaiah         4352410  4352417.0  14070.0   44.0
Karam         6977023  6977030.0  14082.0   44.0
Karena        2660194  2660199.0  10031.0   44.0
Kelani        3773286  3773293.0  14054.0   44.0
Kobi          5659836  5659843.0  14055.0   44.0
Latoya        7626610  7626617.0  14041.0   44.0
Marlenne      3222696  3222702.0  12044.0   44.0
Mathilda      3810789  3810796.0  14063.0   44.0
Meher         3276902  3276908.0  12057.0   44.0
Miroslava     3798271  3798278.0  14060.0   44.0
Navy          3891425  3891431.0  12080.0   44.0
Niam          6339908  6339914.0  12081.0   44.0
Nisa          4871385  4871393.0  16071.0   44.0
Oryan         5305991  5305998.0  14058.0   44.0
Price         5939355  5939362.0  14070.0   44.0
Prisilla      3235744  3235750.0  12047.0   44.0
Prudence      4690592  4690599.0  14074.0   44.0
Radha         3818743  3818750.0  14065.0   44.0
Rayvon        6356124  6356131.0  14063.0   44.0
Romi          3814481  3814487.0  12059.0   44.0
Rosselyn      3535288  3535295.0  14052.0   44.0
Satya         3819413  3819420.0  14065.0   44.0
Sherly        3219780  3219786.0  12043.0   44.0
Suhana        3281849  3281855.0  12058.0   44.0
Tera          2762874  2762880.0  12041.0   44.0
Tri           4852127  4852134.0  14058.0   44.0
Uzziah        5365429  5365436.0  14080.0   44.0
Yamilex       4578350  4578358.0  16060.0   44.0